<a href="https://colab.research.google.com/github/HashamHassan-01/flyrank-ml-internship-hasham/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HashamHassan-01/flyrank-ml-internship-hasham/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*
## ML Task Type

Task Type: Scoring (Regression)

The goal is to assign each content page an opportunity score that helps prioritize which pages should be reviewed first for refresh. Pages with higher predicted opportunity should be reviewed before lower-priority pages.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd

df = pd.read_csv("flyrank-ml-internship-hasham/data/raw/content_refresh_anonymized.csv")
print("Dataset Shape:", df.shape)
print("\nFirst 10 columns:")
print(df.columns[:10])

Dataset Shape: (30000, 44)

First 10 columns:
Index(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count',
       'char_count'],
      dtype='object')

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*
## Target or Proxy

The target is a content opportunity score that estimates which pages are most likely to benefit from a content refresh.

Since no direct "refresh success" label exists in the dataset, existing performance metrics such as sessions, CTR, engagement rate, content age, and traffic trends can be used as proxy signals.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df[[
    "sessions_90d",
    "ctr",
    "engagement_rate",
    "content_age_days"
]].head()

   sessions_90d   ctr  engagement_rate  content_age_days
0            17  0.76             5.88               187
1             9  0.05             0.00               445
2            11  0.09             0.00               141
3            78  0.49             1.28               463
4           145  0.13             0.00               263

## 3. Success metric

*One metric you can defend. What number means 'good'?*

## Success Metric

Because this is a scoring problem, a suitable evaluation metric is Mean Absolute Error (MAE). Lower MAE indicates that the predicted opportunity scores are closer to the actual target values.

From a business perspective, success means that the model consistently ranks high-opportunity pages ahead of lower-priority pages, helping the content team focus its review efforts more effectively.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df["sessions_90d"].describe()

count    30000.000000
mean        37.066633
std        107.069131
min          1.000000
25%          2.000000
50%          7.000000
75%         27.000000
max       4345.000000
Name: sessions_90d, dtype: float64

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

## Unit of Analysis

One row in the dataset represents one content page (article). Each row contains information about that page, including search performance, content characteristics, engagement metrics, and historical traffic. The ML model will evaluate each content page individually to determine its priority for refresh.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A simple fixed rule cannot reliably identify which pages should be refreshed because many factors influence content performance. A page may have low traffic but high engagement, or high search volume but strong competition. Machine learning can evaluate multiple signals such as CTR, engagement rate, search volume, content age, historical traffic, and competition together to identify patterns that are difficult to capture with a single if-statement. This allows content teams to prioritize pages more accurately for refresh.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df[[
    "search_volume",
    "competition",
    "ctr",
    "engagement_rate",
    "content_age_days"
]].head()

   search_volume  competition   ctr  engagement_rate  content_age_days
0           10.0         0.67  0.76             5.88               187
1           90.0         0.01  0.05             0.00               445
2            0.0         0.00  0.09             0.00               141
3           10.0         0.00  0.49             1.28               463
4            0.0         0.00  0.13             0.00               263

## Self-check

✅ Every section is filled with markdown and supporting code.

✅ The notebook runs from top to bottom with no errors.

✅ No client names, URLs, or private queries are included.

✅ Your wording is careful (observed, measured, decision-support).

✅ The notebook has been committed under work/notebooks/.