<a href="https://colab.research.google.com/github/HashamHassan-01/flyrank-ml-internship-hasham/blob/main/work/notebooks/w07_action_playbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HashamHassan-01/flyrank-ml-internship-hasham/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

### Ranked action approach

The action playbook uses the validated opportunity score to prioritize pages for human review. The ranking is directional decision-support rather than a prediction of future SEO performance.

The highest-ranked pages are reviewed first because they combine the signals used by the baseline opportunity score: search demand, average position, content age, and CTR. These signals indicate potential opportunity, but they do not prove that a refresh will improve performance.

Each page receives a reason code to explain the main signal behind its recommendation:

- **STALE_CONTENT** — content is older than 365 days.
- **LOW_RANK** — average search position is worse than 20.
- **LOW_CTR** — CTR is below 2%.
- **HIGH_VOLUME** — search volume is above the 75th percentile.
- **MONITOR_SIGNAL** — none of the main reason-code thresholds is triggered.

Actions are prioritized as:

1. **REFRESH_NOW** — highest-scoring pages that warrant early human review.
2. **REFRESH_SOON** — pages with meaningful opportunity but lower priority.
3. **MONITOR** — pages that do not currently justify refresh priority.

The reason code is an explanation aid, not a causal diagnosis. A page can match several signals, but the queue records one primary reason code using a fixed priority order.

In [ ]:
# Build the ranked action queue from the validated baseline scoring logic.

import numpy as np
import pandas as pd

playbook_df = df.copy()

# Normalize the same four signals used by the baseline.
playbook_df["volume_score"] = (
    playbook_df["search_volume"] /
    playbook_df["search_volume"].max()
)

playbook_df["age_score"] = (
    playbook_df["content_age_days"] /
    playbook_df["content_age_days"].max()
)

playbook_df["rank_score"] = (
    playbook_df["avg_position"] /
    playbook_df["avg_position"].max()
)

playbook_df["ctr_score"] = (
    1 - (playbook_df["ctr"] / playbook_df["ctr"].max())
)

# Same baseline opportunity score used in earlier work.
playbook_df["baseline_score"] = (
    0.40 * playbook_df["volume_score"] +
    0.25 * playbook_df["rank_score"] +
    0.20 * playbook_df["age_score"] +
    0.15 * playbook_df["ctr_score"]
)

# Primary reason code.
volume_threshold = playbook_df["search_volume"].quantile(0.75)

conditions = [
    playbook_df["content_age_days"] > 365,
    playbook_df["avg_position"] > 20,
    playbook_df["ctr"] < 2,
    playbook_df["search_volume"] > volume_threshold
]

choices = [
    "STALE_CONTENT",
    "LOW_RANK",
    "LOW_CTR",
    "HIGH_VOLUME"
]

playbook_df["reason_code"] = np.select(
    conditions,
    choices,
    default="MONITOR_SIGNAL"
)

# Action tier.
playbook_df["action"] = np.where(
    playbook_df["baseline_score"] >= 0.70,
    "REFRESH_NOW",
    np.where(
        playbook_df["baseline_score"] >= 0.50,
        "REFRESH_SOON",
        "MONITOR"
    )
)

# Highest opportunity first.
playbook_df = playbook_df.sort_values(
    "baseline_score",
    ascending=False
).reset_index(drop=True)

playbook_df["priority_rank"] = np.arange(1, len(playbook_df) + 1)

# Show the actual queue.
queue_preview = playbook_df[
    [
        "priority_rank",
        "content_id",
        "baseline_score",
        "action",
        "reason_code",
        "search_volume",
        "avg_position",
        "ctr",
        "content_age_days"
    ]
].head(20)

display(queue_preview)

,priority_rank,content_id,baseline_score,action,reason_code,search_volume,avg_position,ctr,content_age_days
0,1,content_ef99c4abd9ab,0.753425,REFRESH_NOW,STALE_CONTENT,74000.0,38.5,0.03,463
1,2,content_5ec29ae79c60,0.692028,REFRESH_SOON,STALE_CONTENT,60500.0,49.8,0.00,463
2,3,content_bf67a444faef,0.687640,REFRESH_SOON,STALE_CONTENT,60500.0,45.5,0.00,463
3,4,content_454cc6654c6e,0.687028,REFRESH_SOON,STALE_CONTENT,60500.0,44.9,0.00,463
4,5,content_deb54e9e19cd,0.683762,REFRESH_SOON,STALE_CONTENT,60500.0,41.7,0.00,463
5,6,content_83e3da1394ac,0.648589,REFRESH_SOON,STALE_CONTENT,49500.0,65.5,0.00,463
6,7,content_cd6760921db8,0.630017,REFRESH_SOON,STALE_CONTENT,49500.0,47.3,0.00,463
7,8,content_ee4630879d03,0.607466,REFRESH_SOON,STALE_CONTENT,49500.0,25.2,0.00,463
8,9,content_f76ccf7a7834,0.584838,REFRESH_SOON,STALE_CONTENT,49500.0,9.5,0.15,445
9,10,content_84fe9d0a707a,0.577287,REFRESH_SOON,STALE_CONTENT,40500.0,43.3,0.00,463
10,11,content_c841193dc692,0.555609,REFRESH_SOON,STALE_CONTENT,40500.0,22.1,0.03,463
11,12,content_8ca50876b0df,0.551732,REFRESH_SOON,STALE_CONTENT,40500.0,18.3,0.03,463
12,13,content_f04ea036f597,0.524604,REFRESH_SOON,STALE_CONTENT,33100.0,30.9,0.02,463
13,14,content_661e1745db72,0.523257,REFRESH_SOON,LOW_RANK,2400.0,245.0,0.00,311
14,15,content_eb1510f4b5f1,0.508103,REFRESH_SOON,STALE_CONTENT,33100.0,14.7,0.00,463
15,16,content_6b41450ae50c,0.504753,REFRESH_SOON,STALE_CONTENT,27100.0,43.2,0.00,463
16,17,content_19bdaa296a9b,0.500496,REFRESH_SOON,STALE_CONTENT,33100.0,13.5,0.00,445
17,18,content_6ef3dcb7be11,0.495766,MONITOR,STALE_CONTENT,27100.0,6.0,0.07,545
18,19,content_b40e32d5df10,0.484915,MONITOR,STALE_CONTENT,22200.0,24.0,0.00,537
19,20,content_6f6a4e56098c,0.484376,MONITOR,STALE_CONTENT,33100.0,3.2,15.56,495

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one.

from pathlib import Path


# Project paths
ROOT = Path("/content/flyrank-ml-internship-hasham")

DATA_PATH = ROOT / "data/raw/content_refresh_anonymized.csv"
OUTPUT_DIR = ROOT / "work/outputs"
FIGURES_DIR = ROOT / "work/figures"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

print("Data:", DATA_PATH)
print("Outputs:", OUTPUT_DIR)
print("Figures:", FIGURES_DIR)

Data: /content/flyrank-ml-internship-hasham/data/raw/content_refresh_anonymized.csv
Outputs: /content/flyrank-ml-internship-hasham/work/outputs
Figures: /content/flyrank-ml-internship-hasham/work/figures

In [ ]:
df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7



### Archetype → action mapping

The action distribution is reviewed across content archetypes to see where the highest-priority pages occur across content types and search intents. Raw counts are shown because the REFRESH_NOW and REFRESH_SOON recommendations are sparse in the 30,000-page dataset. This is descriptive analysis only; it does not imply that a content type or intent causes a particular action.

In [ ]:
archetype_summary = (
    playbook_df.groupby(["content_type", "main_intent"])["action"]
    .value_counts()
    .unstack(fill_value=0)
)

display(archetype_summary)

action                            MONITOR  REFRESH_NOW  REFRESH_SOON
content_type       main_intent
comparison article informational      697            0             0
keyword article    commercial        4611            0             1
                   informational    16522            1            15
                   navigational        46            0             0
                   transactional     5733            0             0

### Content age and refresh signal

Content age is included as one of the opportunity signals because older pages may represent potential refresh opportunities. The ML-09 analysis provides supporting evidence for considering content age in the review process. However, the observed relationship should not be interpreted as proof that refreshing an older page will improve performance. The `STALE_CONTENT` rule therefore acts as a review signal rather than a causal diagnosis.

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

### Intended use

This playbook is intended for content teams or analysts who need a practical way to prioritize pages for human review.

Its purpose is to answer:

> Which pages should be reviewed first for a possible content refresh?

The output is **decision-support**, not an automated SEO decision. The ranked score helps order the review queue using observable signals in the dataset.

### Limits

The playbook does not establish that refreshing a page will increase traffic, rankings, CTR, or conversions.

The model and baseline score are based on a constructed opportunity score rather than an independent business outcome. The ML-09 validation also showed that performance is sensitive to the validation design: the grouped validation produced higher error than the original random split.

Therefore, the ranking should be treated as directional.

The playbook is also limited by the available dataset. It does not fully capture factors such as search-engine algorithm changes, seasonality, competitor actions, technical SEO problems, indexing problems, content quality, search intent changes, or business priorities.

The queue should therefore be used to decide **what to inspect first**, not **what to change automatically**.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

# Basic checks supporting the intended-use statement.

print("Rows in playbook:", len(playbook_df))
print("Unique pages:", playbook_df["content_id"].nunique())
print("Unique clients:", playbook_df["client_id"].nunique())

print("\nAction distribution:")
display(
    playbook_df["action"]
    .value_counts()
    .rename_axis("action")
    .to_frame("count")
)

print("\nReason-code distribution:")
display(
    playbook_df["reason_code"]
    .value_counts()
    .rename_axis("reason_code")
    .to_frame("count")
)

Rows in playbook: 30000
Unique pages: 30000
Unique clients: 32

Action distribution:

              count
action
MONITOR       29983
REFRESH_SOON     16
REFRESH_NOW       1

Reason-code distribution:

                count
reason_code
LOW_CTR         16871
STALE_CONTENT    6360
LOW_RANK         6120
MONITOR_SIGNAL    613
HIGH_VOLUME        36

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

### Human review rules

A person must review a page before any refresh work begins.

For each high-priority recommendation, the reviewer should check:

1. **Current content quality** — Is the page actually outdated, incomplete, inaccurate, or thin?
2. **Search intent** — Does the current page still match the intent behind the target query?
3. **Current ranking context** — Is the page's ranking problem likely to be content-related?
4. **Technical issues** — Could indexing, crawling, canonicalization, or other technical issues explain the weak performance?
5. **Cannibalization** — Are multiple pages targeting the same topic or query?
6. **Recent changes** — Has the page already been updated even if the dataset reports an older content age?
7. **Business value** — Does the topic matter enough to justify the cost of a refresh?
8. **Seasonality or external changes** — Could the observed trend be temporary?


### Cost vs. value

A high opportunity score does not automatically mean that a refresh is worth doing. Refresh work requires writer, editor, analyst, and review time, so business value and expected effort should be considered before action. The current playbook does not explicitly model refresh cost, so this is a known limitation rather than a decision made by the score. Human reviewers should consider the expected value of the page relative to the effort required.


### No-go list

The following decisions should not be automated by this playbook:

- Automatically rewriting or publishing page content.
- Automatically deleting pages.
- Automatically changing titles, URLs, or internal links.
- Automatically deciding that a page will gain traffic after a refresh.
- Automatically overriding editorial or business priorities.
- Automatically treating a low score as proof that a page has no value.
- Automatically acting on pages where technical problems, cannibalization, or unusual search behavior have not been checked.

The system should recommend what to review first. A human remains responsible for deciding whether and how to act.

In [ ]:
# Create a human-review checklist for the top 20 recommendations.

review_queue = playbook_df.head(20)[
    [
        "priority_rank",
        "content_id",
        "baseline_score",
        "action",
        "reason_code",
        "search_volume",
        "avg_position",
        "ctr",
        "content_age_days"
    ]
].copy()

review_queue["human_review_required"] = True

display(review_queue)

,priority_rank,content_id,baseline_score,action,reason_code,search_volume,avg_position,ctr,content_age_days,human_review_required
0,1,content_ef99c4abd9ab,0.753425,REFRESH_NOW,STALE_CONTENT,74000.0,38.5,0.03,463,True
1,2,content_5ec29ae79c60,0.692028,REFRESH_SOON,STALE_CONTENT,60500.0,49.8,0.00,463,True
2,3,content_bf67a444faef,0.687640,REFRESH_SOON,STALE_CONTENT,60500.0,45.5,0.00,463,True
3,4,content_454cc6654c6e,0.687028,REFRESH_SOON,STALE_CONTENT,60500.0,44.9,0.00,463,True
4,5,content_deb54e9e19cd,0.683762,REFRESH_SOON,STALE_CONTENT,60500.0,41.7,0.00,463,True
5,6,content_83e3da1394ac,0.648589,REFRESH_SOON,STALE_CONTENT,49500.0,65.5,0.00,463,True
6,7,content_cd6760921db8,0.630017,REFRESH_SOON,STALE_CONTENT,49500.0,47.3,0.00,463,True
7,8,content_ee4630879d03,0.607466,REFRESH_SOON,STALE_CONTENT,49500.0,25.2,0.00,463,True
8,9,content_f76ccf7a7834,0.584838,REFRESH_SOON,STALE_CONTENT,49500.0,9.5,0.15,445,True
9,10,content_84fe9d0a707a,0.577287,REFRESH_SOON,STALE_CONTENT,40500.0,43.3,0.00,463,True
10,11,content_c841193dc692,0.555609,REFRESH_SOON,STALE_CONTENT,40500.0,22.1,0.03,463,True
11,12,content_8ca50876b0df,0.551732,REFRESH_SOON,STALE_CONTENT,40500.0,18.3,0.03,463,True
12,13,content_f04ea036f597,0.524604,REFRESH_SOON,STALE_CONTENT,33100.0,30.9,0.02,463,True
13,14,content_661e1745db72,0.523257,REFRESH_SOON,LOW_RANK,2400.0,245.0,0.00,311,True
14,15,content_eb1510f4b5f1,0.508103,REFRESH_SOON,STALE_CONTENT,33100.0,14.7,0.00,463,True
15,16,content_6b41450ae50c,0.504753,REFRESH_SOON,STALE_CONTENT,27100.0,43.2,0.00,463,True
16,17,content_19bdaa296a9b,0.500496,REFRESH_SOON,STALE_CONTENT,33100.0,13.5,0.00,445,True
17,18,content_6ef3dcb7be11,0.495766,MONITOR,STALE_CONTENT,27100.0,6.0,0.07,545,True
18,19,content_b40e32d5df10,0.484915,MONITOR,STALE_CONTENT,22200.0,24.0,0.00,537,True
19,20,content_6f6a4e56098c,0.484376,MONITOR,STALE_CONTENT,33100.0,3.2,15.56,495,True

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

### Monitoring and retrain triggers

The playbook should be reconsidered when the data or the decision problem changes.

Recommended triggers are:

- **Data freshness:** the underlying dataset is no longer representative of the period being used for decisions.
- **Feature drift:** search volume, CTR, ranking, or content-age distributions change substantially.
- **Action drift:** the proportion of pages receiving REFRESH_NOW or REFRESH_SOON changes materially without an obvious business reason.
- **Performance drift:** the ranking no longer produces useful candidates during human review.
- **Business-process change:** the content team's definition of a valuable refresh opportunity changes.
- **Search environment change:** major search-engine changes or other external events make historical relationships less reliable.
- **New outcome data:** independent post-refresh outcomes become available.

A retrain or redesign should not be triggered by one unusual page. It should be considered when there is repeated evidence that the current ranking no longer represents useful decision-support.

Because the current target is a constructed score, a future version should preferably be validated against an independent outcome such as measured post-refresh improvement before being treated as a predictive model.

In [ ]:
# Monitoring snapshot for the current playbook.

monitoring_snapshot = {
    "rows": len(playbook_df),
    "unique_pages": playbook_df["content_id"].nunique(),
    "unique_clients": playbook_df["client_id"].nunique(),
    "refresh_now_pct": (
        (playbook_df["action"] == "REFRESH_NOW").mean() * 100
    ),
    "refresh_soon_pct": (
        (playbook_df["action"] == "REFRESH_SOON").mean() * 100
    ),
    "monitor_pct": (
        (playbook_df["action"] == "MONITOR").mean() * 100
    ),
    "median_score": playbook_df["baseline_score"].median()
}

monitoring_snapshot

{'rows': 30000,
 'unique_pages': 30000,
 'unique_clients': 32,
 'refresh_now_pct': np.float64(0.0033333333333333335),
 'refresh_soon_pct': np.float64(0.05333333333333334),
 'monitor_pct': np.float64(99.94333333333333),
 'median_score': 0.24821968772615427}

### Current action distribution

The current queue is highly concentrated in `MONITOR`: approximately 99.94% of pages are classified as MONITOR, while only about 0.057% receive `REFRESH_NOW` or `REFRESH_SOON`. This imbalance should be monitored over time because substantial changes could indicate that the action thresholds need recalibration.

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

### Paper exports

The ranked queue is exported for reuse in the research paper.

The queue is regenerated by the notebook rather than committed to Git because the repository's CI leak-guard keeps data files out of version control.

The exported queue contains the priority rank, action, reason code, score, and the main signals needed to explain why a page appears in the review queue.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

# Export the ranked queue for reuse in the paper.

queue_columns = [
    "priority_rank",
    "content_id",
    "baseline_score",
    "action",
    "reason_code",
    "search_volume",
    "avg_position",
    "ctr",
    "content_age_days"
]

final_queue = playbook_df[queue_columns].copy()

queue_path = OUTPUT_DIR / "content_action_playbook_queue.csv"

final_queue.to_csv(
    queue_path,
    index=False
)

print("Queue exported to:")
print(queue_path)

print("\nTop 10 exported recommendations:")
display(final_queue.head(10))

Queue exported to:
/content/flyrank-ml-internship-hasham/work/outputs/content_action_playbook_queue.csv

Top 10 exported recommendations:

,priority_rank,content_id,baseline_score,action,reason_code,search_volume,avg_position,ctr,content_age_days
0,1,content_ef99c4abd9ab,0.753425,REFRESH_NOW,STALE_CONTENT,74000.0,38.5,0.03,463
1,2,content_5ec29ae79c60,0.692028,REFRESH_SOON,STALE_CONTENT,60500.0,49.8,0.00,463
2,3,content_bf67a444faef,0.687640,REFRESH_SOON,STALE_CONTENT,60500.0,45.5,0.00,463
3,4,content_454cc6654c6e,0.687028,REFRESH_SOON,STALE_CONTENT,60500.0,44.9,0.00,463
4,5,content_deb54e9e19cd,0.683762,REFRESH_SOON,STALE_CONTENT,60500.0,41.7,0.00,463
5,6,content_83e3da1394ac,0.648589,REFRESH_SOON,STALE_CONTENT,49500.0,65.5,0.00,463
6,7,content_cd6760921db8,0.630017,REFRESH_SOON,STALE_CONTENT,49500.0,47.3,0.00,463
7,8,content_ee4630879d03,0.607466,REFRESH_SOON,STALE_CONTENT,49500.0,25.2,0.00,463
8,9,content_f76ccf7a7834,0.584838,REFRESH_SOON,STALE_CONTENT,49500.0,9.5,0.15,445
9,10,content_84fe9d0a707a,0.577287,REFRESH_SOON,STALE_CONTENT,40500.0,43.3,0.00,463

In [ ]:
# Verify that the export exists and can be read back.

assert queue_path.exists(), "Queue export was not created."

check_queue = pd.read_csv(queue_path)

print("Export verified.")
print("Shape:", check_queue.shape)
print("Columns:", check_queue.columns.tolist())

Export verified.
Shape: (30000, 9)
Columns: ['priority_rank', 'content_id', 'baseline_score', 'action', 'reason_code', 'search_volume', 'avg_position', 'ctr', 'content_age_days']

# 5-Minute Demo Outline

## 1. The Problem
Content teams may have thousands of pages, making it difficult to manually decide which pages should be reviewed or refreshed first. My goal was to create a reproducible workflow that prioritizes pages for human review using observable search and content signals.

## 2. The Method
I used an anonymized FlyRank dataset containing 30,000 content pages. The workflow focused on four signals:

- Search volume
- Content age
- Average search position
- Click-through rate (CTR)

These signals were combined into a transparent Opportunity Score. I then evaluated a Random Forest Regressor using client-grouped validation to prevent pages from the same client from appearing in both the training and test sets.

## 3. One Key Finding
The Random Forest achieved strong performance when reproducing the constructed Opportunity Score, with a grouped-test R² of approximately 0.988.

However, an important limitation was identified: the Opportunity Score was constructed from the same features used as model inputs. Therefore, the result shows that the model can reproduce the scoring rule rather than independently predict future SEO performance.

## 4. One Chart
The model-versus-baseline comparison chart shows that the Random Forest produced substantially lower prediction error than the mean baseline on the same client-grouped test split.

## 5. Recommendation
The final output should be used as a decision-support system rather than an automatic decision-maker. The workflow creates a ranked queue of pages for human review, while future post-refresh outcome data would be needed to test whether these recommendations lead to measurable SEO improvement.

---

# Social Post

I built a content-refresh prioritization workflow using an anonymized FlyRank dataset of 30,000 pages.

The workflow combines search volume, content age, average search position, and CTR into a transparent Opportunity Score. I then evaluated a Random Forest using client-grouped validation to avoid overlap between clients in training and testing.

One of the biggest lessons from the project was about honest ML framing: although the model achieved strong performance in reproducing the Opportunity Score, the target itself was constructed from the same input signals. So this does not prove that the model predicts future SEO improvement.

The final result is a decision-support workflow that creates a ranked queue for human content review, with clear limitations and recommendations for future validation.

#MachineLearning #DataScience #AI #SEO #MachineLearningInternship

---

# Employer-Facing Summary

I developed a reproducible machine-learning workflow for prioritizing content pages for human refresh review using an anonymized dataset of 30,000 pages. I combined search volume, content age, average search position, and CTR into a transparent Opportunity Score and evaluated the workflow using client-grouped validation with zero client overlap. The analysis showed that the model could accurately reproduce the constructed scoring system while also identifying an important target-definition limitation, leading to an honest decision-support approach rather than unsupported claims about SEO improvement.

#Self Check

- [x] Every section above is filled — markdown thinking AND the code that backs it.
- [x] The notebook runs top to bottom with no errors (Runtime → Run all).
- [x] No client names, URLs, or private queries anywhere.
- [x] My claims use careful words: observed, measured, directional, decision-support.
- [x] Committed to my repo under `work/notebooks/`.